/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author ASUS PC
 */
public class FarmFrame extends javax.swing.JFrame {
    Kambing mbe;
    /**
     * Creates new form FarmFrame
     */
    public FarmFrame() {
       initComponents();
       mbe = new  Kambing(kambing.getX(),kambing.getY());
       energyBar.setValue(mbe.getEnergy());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
   
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        GamaArea = new javax.swing.JPanel();
        btnEnergy = new javax.swing.JButton();
        btnKiri = new javax.swing.JButton();
        btnBawah = new javax.swing.JButton();
        btnKanan1 = new javax.swing.JButton();
        btnAtas1 = new javax.swing.JButton();
        inputValue = new javax.swing.JTextField();
        inputValueSudut = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnSudut = new javax.swing.JButton();
        btnSound = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        kambing = new javax.swing.JLabel();
        topGUI = new javax.swing.JPanel();
        energyBar = new javax.swing.JProgressBar();
        jLabel4 = new javax.swing.JLabel();
        BG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kambing Game");
        setMinimumSize(new java.awt.Dimension(1000, 600));
        setResizable(false);
        setSize(new java.awt.Dimension(1000, 600));

        jPanel1.setMinimumSize(new java.awt.Dimension(1000, 600));
        jPanel1.setLayout(null);

        GamaArea.setOpaque(false);
        GamaArea.setLayout(null);

        btnEnergy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/plus.png"))); // NOI18N
        btnEnergy.setContentAreaFilled(false);
        btnEnergy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnergyActionPerformed(evt);
            }
        });
        GamaArea.add(btnEnergy);
        btnEnergy.setBounds(17, 195, 80, 70);

        btnKiri.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Return_Button.png"))); // NOI18N
        btnKiri.setContentAreaFilled(false);
        btnKiri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKiriActionPerformed(evt);
            }
        });
        GamaArea.add(btnKiri);
        btnKiri.setBounds(685, 364, 97, 75);

        btnBawah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Return_Button_d.png"))); // NOI18N
        btnBawah.setContentAreaFilled(false);
        btnBawah.setDoubleBuffered(true);
        btnBawah.setFocusCycleRoot(true);
        btnBawah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBawahActionPerformed(evt);
            }
        });
        GamaArea.add(btnBawah);
        btnBawah.setBounds(788, 366, 99, 73);

        btnKanan1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Return_Button_r.png"))); // NOI18N
        btnKanan1.setContentAreaFilled(false);
        btnKanan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKanan1ActionPerformed(evt);
            }
        });
        GamaArea.add(btnKanan1);
        btnKanan1.setBounds(893, 364, 97, 75);

        btnAtas1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Return_Button_u.png"))); // NOI18N
        btnAtas1.setContentAreaFilled(false);
        btnAtas1.setDoubleBuffered(true);
        btnAtas1.setFocusCycleRoot(true);
        btnAtas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtas1ActionPerformed(evt);
            }
        });
        GamaArea.add(btnAtas1);
        btnAtas1.setBounds(788, 285, 99, 73);

        inputValue.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        inputValue.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        inputValue.setText("1");
        inputValue.setBorder(new javax.swing.border.MatteBorder(null));
        inputValue.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        GamaArea.add(inputValue);
        inputValue.setBounds(568, 372, 99, 55);

        inputValueSudut.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        inputValueSudut.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        inputValueSudut.setBorder(new javax.swing.border.MatteBorder(null));
        inputValueSudut.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        GamaArea.add(inputValueSudut);
        inputValueSudut.setBounds(115, 372, 93, 55);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Langkah :");
        GamaArea.add(jLabel1);
        jLabel1.setBounds(568, 344, 85, 22);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Sudut :");
        GamaArea.add(jLabel2);
        jLabel2.setBounds(123, 344, 85, 22);

        btnSudut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Reload_Button.png"))); // NOI18N
        btnSudut.setContentAreaFilled(false);
        btnSudut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSudutActionPerformed(evt);
            }
        });
        GamaArea.add(btnSudut);
        btnSudut.setBounds(10, 356, 99, 75);

        btnSound.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sound.png"))); // NOI18N
        btnSound.setContentAreaFilled(false);
        btnSound.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSoundActionPerformed(evt);
            }
        });
        GamaArea.add(btnSound);
        btnSound.setBounds(17, 275, 80, 70);

        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.setOpaque(false);

        kambing.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sheep.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(652, Short.MAX_VALUE)
                .addComponent(kambing)
                .addGap(254, 254, 254))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(kambing)
                .addContainerGap(280, Short.MAX_VALUE))
        );

        kambing.getAccessibleContext().setAccessibleParent(GamaArea);

        GamaArea.add(jPanel2);
        jPanel2.setBounds(0, 0, 1000, 450);
        jPanel2.getAccessibleContext().setAccessibleParent(jPanel2);

        jPanel1.add(GamaArea);
        GamaArea.setBounds(0, 150, 1000, 450);

        topGUI.setOpaque(false);

        energyBar.setStringPainted(true);

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nenergyBar.png"))); // NOI18N
        jLabel4.setText("Energy :");

        javax.swing.GroupLayout topGUILayout = new javax.swing.GroupLayout(topGUI);
        topGUI.setLayout(topGUILayout);
        topGUILayout.setHorizontalGroup(
            topGUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topGUILayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(energyBar, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 553, Short.MAX_VALUE))
        );
        topGUILayout.setVerticalGroup(
            topGUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topGUILayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(topGUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(energyBar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap(75, Short.MAX_VALUE))
        );

        jPanel1.add(topGUI);
        topGUI.setBounds(0, 0, 1000, 150);

        BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bg-lite.jpg"))); // NOI18N
        BG.setAlignmentY(0.0F);
        jPanel1.add(BG);
        BG.setBounds(0, 0, 1000, 600);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKanan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKanan1ActionPerformed
       int n = getN();
        if(insidePanel(mbe.getX()+(25*n), mbe.getY()) && mbe.getEnergy() > 0){
            kambing.setLocation(mbe.right(n),mbe.getY());
            mbe.minEnergy();
            energyBar.setValue(mbe.getEnergy());
        }
    }//GEN-LAST:event_btnKanan1ActionPerformed

    private void btnSudutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSudutActionPerformed
        double n = getN();
        mbe.sudut(Double.parseDouble(inputValueSudut.getText()), 25*n);
        kambing.setLocation(mbe.getX(), mbe.getY());
        energyBar.setValue(mbe.getEnergy());
    }//GEN-LAST:event_btnSudutActionPerformed

    private void btnKiriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKiriActionPerformed
        int n = getN();
        if(insidePanel(mbe.getX()-(25*n), mbe.getY()) && mbe.getEnergy() > 0){
            kambing.setLocation(mbe.left(n),mbe.getY());
            mbe.minEnergy();
            energyBar.setValue(mbe.getEnergy());
        }
    }//GEN-LAST:event_btnKiriActionPerformed

    private void btnAtas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtas1ActionPerformed
        int n = getN();
        if(insidePanel(mbe.getX(), mbe.getY()-(25*n))&& mbe.getEnergy() > 0){
            kambing.setLocation(mbe.getX(),mbe.up(n));
            mbe.minEnergy();
            energyBar.setValue(mbe.getEnergy());
        }
    }//GEN-LAST:event_btnAtas1ActionPerformed

    private void btnBawahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBawahActionPerformed
        int n = getN();
        if(insidePanel(mbe.getX(), mbe.getY()+(25*n))&& mbe.getEnergy() > 0){
            kambing.setLocation(mbe.getX(),mbe.down(n));
            mbe.minEnergy();
            energyBar.setValue(mbe.getEnergy());
        }
    }//GEN-LAST:event_btnBawahActionPerformed

    private void btnSoundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSoundActionPerformed
        mbe.playSound();
        mbe.minEnergy();
        energyBar.setValue(mbe.getEnergy());
    }//GEN-LAST:event_btnSoundActionPerformed

    private void btnEnergyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnergyActionPerformed
        mbe.addEnergy();
        energyBar.setValue(mbe.getEnergy());
    }//GEN-LAST:event_btnEnergyActionPerformed
     public int getN(){
        double n = Double.parseDouble(inputValue.getText());
        if(inputValue.getText().equals(""))
            return 1;
        else
            return (int)n;
    }
    /**
     * @param args the command line arguments
     */
    private boolean insidePanel (int x, int y){
        return ((x>0 && x<915)&& (y > 0 && y < 330));
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FarmFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FarmFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FarmFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FarmFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FarmFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG;
    private javax.swing.JPanel GamaArea;
    private javax.swing.JButton btnAtas1;
    private javax.swing.JButton btnBawah;
    private javax.swing.JButton btnEnergy;
    private javax.swing.JButton btnKanan1;
    private javax.swing.JButton btnKiri;
    private javax.swing.JButton btnSound;
    private javax.swing.JButton btnSudut;
    private javax.swing.JProgressBar energyBar;
    private javax.swing.JTextField inputValue;
    private javax.swing.JTextField inputValueSudut;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel kambing;
    private javax.swing.JPanel topGUI;
    // End of variables declaration//GEN-END:variables
   
}
